In [4]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(52)
    for ind, x in enumerate(name):
        arr[ord(x)-ord('a')] += 1
    return arr


my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())
y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=100, min_samples_split=2)
    clf.fit(Xtr, ytr)
    print np.mean(clf.predict(Xte) == yte) 


0.690232056125
0.692390717755
0.693739881274
0.688073394495
0.694819212089


In [5]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(52)
    for ind, x in enumerate(name):
        arr[ord(x)-ord('a')] += 1
        arr[ord(x)-ord('a')+26] += ind+1
    return arr


my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())

y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=100, min_samples_split=2)
    clf.fit(Xtr, ytr)
    print np.mean(clf.predict(Xte) == yte) 


0.766864543983
0.760388559093
0.766864543983
0.76740420939
0.759848893686


In [9]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(52+26*26)
    # Iterate each character
    for ind, x in enumerate(name):
        arr[ord(x)-ord('a')] += 1
        arr[ord(x)-ord('a')+26] += ind+1
    # Iterate every 2 characters
    for x in xrange(len(name)-1):
        ind = (ord(name[x])-ord('a'))*26 + (ord(name[x+1])-ord('a')) + 52
        arr[ind] += 1
    return arr

my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())

y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=100, min_samples_split=2)
    clf.fit(Xtr, ytr)
    print np.mean(clf.predict(Xte) == yte) 


[ 26  30  39   0  34  37  40  43  50 390]
0.78548300054
[26 30 39  0 40 37 34 50 43  4]
0.771451699946
[26  0 30 39 34 50 37 43 40  4]
0.783864004317
[ 26  39   0  30  34  40  50  37  43 390]
0.777388019428
[ 26  39  30   0  37  50  34  40  43 390]
0.77172153265


In [31]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(52+26*26+3)
    # Iterate each character
    for ind, x in enumerate(name):
        arr[ord(x)-ord('a')] += 1
        arr[ord(x)-ord('a')+26] += ind+1
    # Iterate every 2 characters
    for x in xrange(len(name)-1):
        ind = (ord(name[x])-ord('a'))*26 + (ord(name[x+1])-ord('a')) + 52
        arr[ind] += 1
    # Last character
    arr[-3] = ord(name[-1])-ord('a')+1
    # Second Last character
    arr[-2] = ord(name[-2])-ord('a')+1
    # Length of name
    arr[-1] = len(name)
    return arr
my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())

y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=100, min_samples_split=2)
    clf.fit(Xtr, ytr)
    print np.mean(clf.predict(Xte) == yte) 


0.803561791689
0.807879114949
0.796276308689
0.804641122504
0.807609282245


In [32]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(52+26*26+3)
    # Iterate each character
    for ind, x in enumerate(name):
        arr[ord(x)-ord('a')] += 1
        arr[ord(x)-ord('a')+26] += ind+1
    # Iterate every 2 characters
    for x in xrange(len(name)-1):
        ind = (ord(name[x])-ord('a'))*26 + (ord(name[x+1])-ord('a')) + 52
        arr[ind] += 1
    # Last character
    arr[-3] = ord(name[-1])-ord('a')+1
    # Second Last character
    arr[-2] = ord(name[-2])-ord('a')+1
    # Length of name
    arr[-1] = len(name)
    return arr

my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())

y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=150, min_samples_split=20)
    clf.fit(Xtr, ytr)
    print clf.feature_importances_.argsort()[-10:][::-1]
    print np.mean(clf.predict(Xte) == yte) 


[728  26 729   0  40  50  30 390  39  37]
0.814085267134
[728  26 729  50   0  40  37  30  34 390]
0.821370750135
[728  26 729  50  40   0  37  30  39 390]
0.818402590394
[728  26 729   0  50  40  30  37 390  39]
0.825148407987
[728  26 729   0  50  40  30  37  39  34]
0.82245008095


In [35]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(1)
    arr[0] = ord(name[-1])-ord('a')+1
    return arr

my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())

y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=150, min_samples_split=20)
    clf.fit(Xtr, ytr)
    print np.mean(clf.predict(Xte) == yte) 


0.771451699946
0.7536427415
0.753912574204
0.7536427415
0.760658391797


In [34]:
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def name_count(name):
    arr = np.zeros(3)
    arr[0] = ord(name[-1])-ord('a')+1
    arr[1] = ord(name[-2])-ord('a')+1
    # Order of a's
    for ind, x in enumerate(name):
        if x == 'a':
            arr[2] += ind+1
    
    return arr

my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])

name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xlist = name_map(my_data['name'])
X = np.array(Xlist.tolist())

y = my_data['gender']

for x in xrange(5):
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
    clf = RandomForestClassifier(n_estimators=150, min_samples_split=20)
    clf.fit(Xtr, ytr)
    print np.mean(clf.predict(Xte) == yte) 
    



0.798165137615
0.794117647059
0.795736643281
0.801133297356
0.803561791689


In [42]:
def name_count(name):
    arr = np.zeros(3)
    arr[0] = ord(name[-1])-ord('a')+1
    arr[1] = ord(name[-2])-ord('a')+1
    # Order of a's
    for ind, x in enumerate(name):
        if x == 'a':
            arr[2] += ind+1
    
    return arr

my_data = np.genfromtxt('names/yob2014.txt', 
                        delimiter=',', 
                        dtype=[('name','S50'), ('gender','S1'),('count','i4')],
                        converters={0: lambda s:s.lower()})
my_data = np.array([row for row in my_data if row[2]>=20])
name_map = np.vectorize(name_count, otypes=[np.ndarray])
Xname = my_data['name']
Xlist = name_map(Xname)
X = np.array(Xlist.tolist())

y = my_data['gender']

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.33)
clf = RandomForestClassifier(n_estimators=150, min_samples_split=20)
clf.fit(Xtr, ytr)

idx = np.random.choice(np.arange(len(Xlist)), 10, replace=False)
xs = Xname[idx]
ys = y[idx]
pred = clf.predict(X[idx])

for a,b, p in zip(xs,ys, pred):
    print a,b, p


shea F F
lucero F M
damiyah F F
nitya F F
sloan M M
porter F M
jalaya F F
aubry F F
mamie F F
jair M M
